[package]
name = "riscv-rust-blink"
version = "0.1.0"
authors = ["Tiwalun <dominik.boehi@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fomu-rt  = "0.0.3"
fomu-pac = "0.0.1"

panic-halt = "0.2"
